#!/bin/sh
### BEGIN INIT INFO
# Provides: hs485d
# RequiredStart: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts hs485d.
# Description: Starts hs485d.
### END INIT INFO

DESC="wired daemon"
NAME="hs485d"
. /lib/lsb/init-functions

LOGLEVEL_HS485D=5

CFG_TEMPLATE_DIR=/etc/config_templates

init() {
	if [ ! -e /etc/config/syslog ] ; then
		cp $CFG_TEMPLATE_DIR/syslog /etc/config
	fi

	if [ -e /etc/config/syslog ] ; then
		. /etc/config/syslog
	fi
}

start() {
	log_daemon_msg "Starting ${DESC}" "${NAME}"
	init
	start-stop-daemon -S -q --exec /bin/hs485dLoader -- -l $LOGLEVEL_HS485D -dw /etc/config/hs485d.conf 
	log_end_msg 0
}
stop() {
	log_daemon_msg "Stopping ${DESC}" "${NAME}"
	start-stop-daemon -K -q -p /var/run/hs485dLoader.pid
	killall hs485d
	rm -f /var/run/hs485dLoader.pid
	log_end_msg 0
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

