#!/bin/sh
### BEGIN INIT INFO
# Provides: lighttpd
# RequiredStart: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts lighttpd webserver.
# Description: Starts lighttpd webserver.
### END INIT INFO

DESC="webserver"
NAME="lighttpd"
. /lib/lsb/init-functions

start() {
	log_daemon_msg "Starting ${DESC}" "${NAME}"
	start-stop-daemon -S -q -p /var/run/lighttpd.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf -m /lib/lighttpd
	log_end_msg 0

	if [ -f /etc/config/server.pem ] ; then
	log_daemon_msg "Starting ${DESC} with SSL support" "${NAME}"
		start-stop-daemon -S -q -p /var/run/lighttpd_ssl.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd_ssl.conf -m /lib/lighttpd
		log_end_msg 0
	fi
}
stop() {
	log_daemon_msg "Stopping ${DESC}" "${NAME}"
	start-stop-daemon -K -q -p /var/run/lighttpd.pid
	start-stop-daemon -K -q -p /var/run/lighttpd_ssl.pid
	log_end_msg 0
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
