#!/bin/sh
### BEGIN INIT INFO
# Provides: eq3configd
# RequiredStart: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts eq3configd.
# Description: Starts eq3configd, eQ-3 service for netfinder.
### END INIT INFO

DESC="eQ-3 service for netfinder"
NAME="eq3configd"
. /lib/lsb/init-functions

init () {
	#radio_mac=$(cat /sys/module/plat_eq3ccu2/parameters/radio_mac)
	#board_serial=$(cat /sys/module/plat_eq3ccu2/parameters/board_serial)
	echo "BidCoS-Address=0x1e3585" > /var/ids
	echo "SerialNumber=JEQ0739200" >> /var/ids
	if [ ! -e /etc/config/ids ] ; then
  	cp /var/ids /etc/config
	fi
	
	if [ ! -e /etc/config/crypttool.cfg ] ; then
		touch /etc/config/crypttool.cfg
	fi
}

start() {
	log_daemon_msg "Starting ${DESC}" "${NAME}"
	init
	start-stop-daemon -S -q -p /var/run/eq3configd.pid --exec /bin/eq3configd &
	log_end_msg 0
}
stop() {
	log_daemon_msg "Stopping ${DESC}" "${NAME}"
	start-stop-daemon -K -q -p /var/run/eq3configd.pid
	log_end_msg 0
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

