#!/bin/sh
### BEGIN INIT INFO
# Provides: rfd
# RequiredStart: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts rfd.
# Description: Starts rfd.
### END INIT INFO

DESC="rf daemon"
NAME="rfd"
. /lib/lsb/init-functions

LOGLEVEL_RFD=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/rfd.pid

init() {
	if [ ! -d /etc/config/rfd ] ; then
		mkdir /etc/config/rfd
	fi
	#Migration for existing rfd.conf in user space
	if [ ! -e /etc/config/rfd.conf ] ; then
		cp $CFG_TEMPLATE_DIR/rfd.conf /etc/config/
	else
    # disable the whole [Interface 0] part
    sed -i -e '/^\[Interface 0\]/,/^\s*$/ s/^/#/' /etc/config/rfd.conf
    sed -i -e 's/^#\s*$//' /etc/config/rfd.conf

		if ! grep -q "Improved Coprocessor Initialization" /etc/config/rfd.conf ; then
			sed -i 's/#\[Interface 0\]/Improved\ Coprocessor\ Initialization\ =\ true\n\n&/' /etc/config/rfd.conf || true
		fi
	fi
	
	#any interface activated in rfd.conf?
	if grep -q -P "^\[Interface" /etc/config/rfd.conf ; then
		#if yes check if BidCos-RF is in interfaces.xml
		if ! grep -q "BidCos-RF" /etc/config/InterfacesList.xml ; then
			sed -i '/<interfaces/ a \\t<ipc>\n\t \t<name>BidCos-RF<\/name>\n\t \t<url>xmlrpc_bin:\/\/127.0.0.1:2001<\/url> \n\t \t<info>BidCos-RF<\/info> \n\t<\/ipc>' /etc/config/InterfacesList.xml
		fi
	else
		#rfd not activated, check if bidcos present in interfaces.xml and remove if so
		if grep -q "BidCos-RF" /etc/config/InterfacesList.xml ; then
			sed -i ':a;N;$!ba;s/\n/|/g;s/|\t<ipc>/\n\t<ipc>/g;' /etc/config/InterfacesList.xml
			sed -i '/BidCos-RF/ d;s/|/\n/g' /etc/config/InterfacesList.xml
		fi
	fi

	if [ ! -e /etc/config/syslog ] ; then
		cp $CFG_TEMPLATE_DIR/syslog /etc/config/
	fi
	if [ -e /etc/config/syslog ] ; then
  		. /etc/config/syslog
	fi
}

waitStartupComplete() {
	log_progress_msg "Waiting for rfd to get ready"
	STEPS=60
	for i in $(seq 1 $STEPS)
	do
		sleep 2
		log_progress_msg "."
    RFDSTATUSPID=`cat /var/status/rfd.status 2>/dev/null`
    RFDPID=`pidof rfd`
    if [ "$RFDSTATUSPID" = "$RFDPID" ] 
		then
			log_end_msg 0
			break
		fi
		if [ $i -eq $STEPS ] 
		then
			log_failure_msg "Timeout while waiting for rfd to get ready"
		fi
	done
}

start() {
	init
	if grep -q -P "^\[Interface" /etc/config/rfd.conf ; then
		log_daemon_msg "Starting ${DESC}" "${NAME}"
		start-stop-daemon -S -q -b -m -p $PIDFILE --exec /bin/rfd -- -f /etc/config/rfd.conf -l $LOGLEVEL_RFD
		waitStartupComplete
	else
		log_daemon_msg "NOT starting ${DESC} because no BidCos-RF hardware present (maybe you want to add [Interface X] section in rfd.conf)?" "${NAME}"
		log_end_msg 0
	fi
}
stop() {
	log_daemon_msg "Stopping ${DESC}" "${NAME}"
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	log_end_msg 0
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

