#!/bin/sh
### BEGIN INIT INFO
# Provides: eq3configcmd
# RequiredStart: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts eq3configcmd update-lgw-firmware for RF- and Wired-Gateways.
# Description: Starts eq3configcmd update-lgw-firmware for RF- and Wired-Gateways.
### END INIT INFO

. /lib/lsb/init-functions
CFG_TEMPLATE_DIR=/etc/config_templates

start() {
	#waitForIP

	if [ ! -e /etc/config/crRFD/hmip_user.conf ] ; then
		cp $CFG_TEMPLATE_DIR/crRFD/hmip_user.conf /etc/config/crRFD/
	fi

	updateHmIPRFUSBStick
	updateCopro
	updateRFFirmware
	updateWiredFirmware
}

waitForIP() {
	for i in `seq 1 10`
	do
		if [ -f /var/status/hasIP ] ; then
			break;
		fi 
		sleep 1
	done	
}

updateCopro() {
	echo "Updating RF Lan Gateway Coprocessor Firmware" | logger -p user.info 
	log_daemon_msg "Updating RF Lan Gateway Coprocessor Firmware" "eq3configcmd update-coprocessor -lgw"
	/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1 >/dev/null
	log_end_msg 0
}

updateHmIPRFUSBStick() {
  if lsusb | grep -q 1b1f:c020; then
    for i in $(find /sys/bus/usb/devices/usb*/ -maxdepth 4 -name "ttyUSB*"); do
      DEVDIR=$(dirname $i)
      if [ -f "${DEVDIR}/uevent" ]; then
        if grep -q PRODUCT=1b1f/c020 ${DEVDIR}/uevent; then
          log_daemon_msg "Check HmIP-RFUSB Firmware for update"
          USBDEV=/dev/$(basename $i)
          log_progress_msg "found dev ${USBDEV}"
          FROM_VERSION=$(/usr/bin/java -jar /opt/HmIP/hmip-copro-update.jar -p ${USBDEV} -v 2>/dev/null | grep "Application version =" | cut -d' ' -f5)
          log_progress_msg ", has version ${FROM_VERSION}"
          TO_VERSION=$(ls /firmware/HmIP-RFUSB/hmip_coprocessor_update-*.eq3 | sed 's/.*hmip_coprocessor_update-\(.*\)\.eq3/\1/' | tail -n1)
          log_progress_msg ", should have version ${TO_VERSION}"
          if [ "${FROM_VERSION}" != "${TO_VERSION}" ]; then
            echo "updating HmIP-RFUSB device ${USBDEV} from Firmware ${FROM_VERSION} to ${TO_VERSION}" | logger -p user.info 
            log_progress_msg "updating"
            /usr/bin/java -jar /opt/HmIP/hmip-copro-update.jar -p $USBDEV -f /firmware/HmIP-RFUSB/hmip_coprocessor_update-${TO_VERSION}.eq3
          else
            log_progress_msg "is already up to date"
          fi
          if [ -f /etc/config/crRFD/hmip_user.conf ] ; then
            sed -i "s|Adapter\.1\.Port=.*|Adapter\.1\.Port=${USBDEV}|" /etc/config/crRFD/hmip_user.conf
          else
          	echo "Adapter.1.Port=${USBDEV}" >/etc/config/crRFD/hmip_user.conf
          fi
          log_end_msg 0
          break
        fi
      fi
    done
  fi
}

updateRFFirmware() {
	echo "Updating RF Lan Gateway Firmware" | logger -p user.info 
	log_daemon_msg "Updating RF Lan Gateway Firmware" "eq3configcmd update-lgw-firmware -m"
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 1  >/dev/null
	log_end_msg 0
}

updateWiredFirmware() {
	echo "Updating Wired Lan Gateway Firmware" | logger -p user.info 
	log_daemon_msg "Updating Wired Lan Gateway Firmware" "eq3configcmd update-lgw-firmware -m"
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 1 >/dev/null
	log_end_msg 0
}
#| logger -t update-lgw-firmware -p user.info
stop() {
	echo "" >/dev/null
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
