#!/bin/sh
### BEGIN INIT INFO
# Provides: HMServer
# RequiredStart: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts HMServer.
# Description: Starts HMServer.
### END INIT INFO

LOGLEVEL_HMServer=5
CFG_TEMPLATE_DIR=/etc/config_templates
PIDFILE=/var/run/HMIPServer.pid
STARTWAITFILE=/var/status/HMServerStarted

DESC="HMServer-service"
NAME="HMServer"
. /lib/lsb/init-functions

init() {
	#export TZ=`cat /etc/config/TZ | cut -d'-' -f1 | cut -d'+' -f1`
	export JAVA_HOME=/usr
	export PATH=$PATH:$JAVA_HOME/bin
	if [ ! -e /etc/config/log4j.xml ] ; then
		cp $CFG_TEMPLATE_DIR/log4j.xml /etc/config/
	fi
	if [ ! -e /etc/config/hmip_networkkey.conf ] ; then
		cp $CFG_TEMPLATE_DIR/hmip_networkkey.conf /etc/config/
	fi
	if [ -d /etc/config/crRFD ] ; then
		mkdir -p /etc/config/crRFD
	fi
	if [ ! -e /etc/config/crRFD/hmip_user.conf ] ; then
		cp $CFG_TEMPLATE_DIR/crRFD/hmip_user.conf /etc/config/crRFD/
	fi
}

start() {
	log_daemon_msg "Starting ${DESC}" "${NAME}"
	init
	start-stop-daemon -S -q -m -p $PIDFILE --exec /usr/bin/java -- -Xmx64m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -jar /opt/HMServer/HMIPServer.jar /etc/crRFD.conf &
	log_progress_msg "Waiting for HMServer to get ready"
	eq3configcmd wait-for-file -f $STARTWAITFILE -p 5 -t 300
	log_end_msg 0
}
stop() {
	log_daemon_msg "Stopping ${DESC}" "${NAME}"
	rm -f $STARTWAITFILE
	start-stop-daemon -K -q -p $PIDFILE
	rm -f $PIDFILE
	log_end_msg 0
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

