#!/bin/sh
### BEGIN INIT INFO
# Provides: eq3configcmd
# RequiredStart: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts eq3configcmd setlgwkey.
# Description: Starts eq3configcmd setlgwkey.
### END INIT INFO

CFG_DIR=/etc/config

start() {
#	init
	/bin/setlgwkey.sh
}

stop() {
	echo "" >/dev/null
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
