#!/bin/sh
### BEGIN INIT INFO
# Provides: eq3configcmd
# RequiredStart: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Starts eq3configcmd update-lgw-firmware for RF- and Wired-Gateways.
# Description: Starts eq3configcmd update-lgw-firmware for RF- and Wired-Gateways.
### END INIT INFO

. /lib/lsb/init-functions

start() {
	#waitForIP
	#updateHmIPRFUSBStick
	updateCopro
	updateRFFirmware
	updateWiredFirmware
}

waitForIP() {
	for i in `seq 1 10`
	do
		if [ -f /var/status/hasIP ] ; then
			break;
		fi 
		sleep 1
	done	
}

updateCopro() {
	echo "Updating RF Lan Gateway Coprocessor Firmware" | logger -p user.info 
	log_daemon_msg "Updating RF Lan Gateway Coprocessor Firmware" "eq3configcmd update-coprocessor -lgw"
	/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1
	log_end_msg 0
}

updateHmIPRFUSBStick() {
	if [ -e /dev/ttyUSB0 ]
	then
		echo "Updating HmIP-RFUSB Firmware" | logger -p user.info 
		log_daemon_msg "Updating HmIP-RFUSB Firmware" "hmip-copro-update.jar -p /dev/ttyUSB0 -f /firmware/HmIP-RFUSB/hmip_coprocessor_update-2.8.4.eq3"
		/usr/bin/java -jar /opt/HmIP/hmip-copro-update.jar -p /dev/ttyUSB0 -f /firmware/HmIP-RFUSB/hmip_coprocessor_update-2.8.4.eq3
		log_end_msg 0
	fi
}

updateRFFirmware() {
	echo "Updating RF Lan Gateway Firmware" | logger -p user.info 
	log_daemon_msg "Updating RF Lan Gateway Firmware" "eq3configcmd update-lgw-firmware -m"
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 1 
	log_end_msg 0
}

updateWiredFirmware() {
	echo "Updating Wired Lan Gateway Firmware" | logger -p user.info 
	log_daemon_msg "Updating Wired Lan Gateway Firmware" "eq3configcmd update-lgw-firmware -m"
	/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/hs485d.conf -l 1
	log_end_msg 0
}
#| logger -t update-lgw-firmware -p user.info
stop() {
	echo "" >/dev/null
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
